enum Resolution {LOW, HIGH};

union HumidityUnion 
	switch (Resolution){
		case LOW:
			short shortHumidity;
		case HIGH:
			float floatHumidity;
		
};

struct PercisionCommand{
	Resolution requestedResolution;
};

struct ResolutionCommand{
	short SensorID; 	//@key
	HumidityUnion humidity;
};

